spring:
  profiles:
    active: mysql
  application:
    name:jpa
  datasource:
    url: jdbc:postgresql://localhost:5432/data_jpa
    username: postgres
    password: abcd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
